services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    networks:
      - app-network

  tui:
    build:
      context: ./tui
    network_mode: host

networks:
  app-network:
    driver: bridge
